name: Discord Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"  # každých 5 hodin restart

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: node index.js
